### PR TITLE
ci: :ferris_wheel: fix macOS CI (restore build deps cache)

### PR DESCRIPTION
**Pull request by darvid**

### CODE REVIEW

**Comment by naikaayushnz** [comment]
Looks like cp linux builds are stuck
https://github.com/darvid/python-hyperscan/actions/runs/7736342623

**Comment by naikaayushnz** [comment]
That seems to have fixed it, thanks! @darvid 
Did the publish fail because of the wheels or some intermittent connection issue on Github 
https://github.com/darvid/python-hyperscan/actions/runs/7736838285

**Comment by naikaayushnz** [comment]
Hi @darvid, apologies for bugging you 
The release was skipped for this PR merge, so the releases don't have the linux cp arm wheels

**Comment by darvid** [comment]
@naikaayushnz yeah sorry, evidently python-semantic-release doesn't have an option to ignore existing release artifacts when publishing to GH so I had to delete the GH release manually and re-run.

all wheels should be up on both github and pypi now. let me know if you have any other issues!

**Comment by naikaayushnz** [comment]
Perfect! @darvid 
Thank you very much! Really appreciate this! 
I've been trying to compile this using vectorscan for months now!

**Pull request merged**
