### PR TITLE
build: :package: update cibuildwheel configuration to support aarch64

### PR DESCRIPTION
**Pull request by darvid**

### CODE REVIEW

**Comment by naikaayushnz** [comment]
Hi @darvid, will there be a v0.8.0 that adds support for linux arm? Currently I see that only macos arm wheels are part of v0.7.0

**Comment by darvid** [comment]
yes i will hopefully add aarch64 linux wheels today, should be the same release version (0.7.0)

**Comment by naikaayushnz** [comment]
Hi @darvid, just saw the linux arm wheels, thank you for this. Also noticed that the wheels for linux are not for CPython and only PyPy, will cp wheels be added?

**Comment by darvid** [comment]
aahhh running into some weird cache issues with github actions, standby

**Comment by darvid** [comment]
in the meantime the cpython/arm wheels do appear to have been built, you should be able to manually download them from here: https://github.com/darvid/python-hyperscan/actions/runs/7735299242

**Pull request merged**
