### PR TITLE
Add support for Python 3.13

### LINKED ISSUE #157: please add wheels for python 3.13
yes ok it was released this week, but I wonder if you could build wheels for python 3.13, so that we could update to this version.

### PR DESCRIPTION
**Pull request by jameshilliard**
Fixes #157.

### CODE REVIEW

**Comment by darvid** [comment]
thanks for the quick PR!

i'm guessing the lint workflow file is being run off of main which is the reason it's not picking up the version update. would you mind making a separate PR to update the CI action versions, and I'll go ahead and approve that? then I'll disable the main branch protection momentarily to test the build before merging this.

**Comment by jameshilliard** [comment]
> would you mind making a separate PR to update the CI action versions, and I'll go ahead and approve that?

Split those changes out into #159.

**Comment by jameshilliard** [comment]
Yep, looks like that fixed it, I rebased this PR as well.

**Comment by darvid** [comment]
not sure why i can't trigger a workflow off this branch despite workflow_dispatch allowed in the GH actions for the wheels workflow, so gonna just merge and pray it works :) will have time to troubleshoot issues/cut a release (if the automated release action fails) later tonight

**Comment by jameshilliard** [comment]
> not sure why i can't trigger a workflow off this branch despite workflow_dispatch allowed in the GH actions for the wheels workflow

Maybe related to these conditionals `github.repository == 'darvid/python-hyperscan'` since the PR is coming from a different repo?

**Comment by jameshilliard** [comment]
> will have time to troubleshoot issues/cut a release (if the automated release action fails) later tonight

Get a chance to look at that?

**Comment by darvid** [comment]
standby sorry, CI issues with the release process

had to fix a bunch of macos build issues which was blocking the release

**Comment by darvid** [comment]
Released

**Pull request merged**
